POST /WebGoat/BypassRestrictions/frontendValidation?error=jj&field1=kk&field2=jj&field3=ii&field4=hh&field5=gg&field6=ff&field7=ee HTTP/1.1
Host: 127.0.0.1:8080
Jazzer-Internal-Controller-Id: -1081961667

