POST /WebGoat/login HTTP/1.1
Host: 172.17.0.4:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 35
Origin: http://localhost:8080
Connection: keep-alive
Referer: http://localhost:8080/WebGoat/login
Cookie: JSESSIONID=7IyGdAZ9l_YmZpBJ4_gkd9EfYm0oIHR-NXRp1D2Z
Upgrade-Insecure-Requests: 1
DNT: 1
Sec-GPC: 1

username=testuser&password=testuser